# Dockerfile
FROM node:20-alpine
#args
ARG KINDE_CLIENT_ID
ARG KINDE_CLIENT_SECRET
ARG KINDE_ISSUER_URL
ARG KINDE_SITE_URL
ARG KINDE_POST_LOGOUT_REDIRECT_URL
ARG KINDE_POST_LOGIN_REDIRECT_URL
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG NEXT_PUBLIC_PUSHER_APP_KEY
ARG PUSHER_APP_ID
ARG PUSHER_APP_KEY
ARG PUSHER_APP_SECRET
ARG PUSHER_APP_CLUSTER
#env
ENV KINDE_CLIENT_ID=${KINDE_CLIENT_ID}
ENV KINDE_CLIENT_SECRET=${KINDE_CLIENT_SECRET}
ENV KINDE_ISSUER_URL=${KINDE_ISSUER_URL}
ENV KINDE_SITE_URL=${KINDE_SITE_URL}
ENV KINDE_POST_LOGOUT_REDIRECT_URL=${KINDE_POST_LOGOUT_REDIRECT_URL}
ENV KINDE_POST_LOGIN_REDIRECT_URL=${KINDE_POST_LOGIN_REDIRECT_URL}
ENV UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
ENV UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
ENV NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV NEXT_PUBLIC_PUSHER_APP_KEY=${NEXT_PUBLIC_PUSHER_APP_KEY}
ENV PUSHER_APP_ID=${PUSHER_APP_ID}
ENV PUSHER_APP_KEY=${PUSHER_APP_KEY}
ENV PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
ENV PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}

WORKDIR /usr/src/app
COPY . .

RUN npm install


RUN npm run build
EXPOSE 3000

CMD ["npm", "start"]